export const APP_MOUNTED = 'APP_MOUNTED'
export const APP_START_FAILED = 'APP_START_FAILED'
export const APP_START_SUCCEDED = 'APP_START_SUCCEDED'

export const USER_CLICKED_PAUSE = 'USER_CLICKED_PAUSE'
export const USER_CLICKED_RESUME = 'USER_CLICKED_RESUME'

export const USER_TURNED_REPEAT_ON = 'USER_TURNED_REPEAT_ON'
export const USER_TURNED_REPEAT_OFF = 'USER_TURNED_REPEAT_OFF'

export const USER_TURNED_SHUFFLE_ON = 'USER_TURNED_SHUFFLE_ON'
export const USER_TURNED_SHUFFLE_OFF = 'USER_TURNED_SHUFFLE_OFF'

export const USER_CHANGED_VOLUME = 'USER_CHANGED_VOLUME'

export const USER_BEGAN_TO_SEEK = 'USER_BEGAN_TO_SEEK'
export const USER_STOPED_TO_SEEK = 'USER_STOPED_TO_SEEK'

export const USER_CLICKED_PLAY_ALBUM = 'USER_CLICKED_ON_PLAY_ALBUM'
export const USER_CLICKED_ADD_ALBUM = 'USER_CLICKED_ON_ADD_ALBUM'

export const USER_CLICKED_REMOVE_TRACK_FROM_PLAYLIST = 'USER_CLICKED_REMOVE_TRACK_FROM_PLAYLIST'
export const USER_CLICKED_CLEAR_PLAYLIST = 'USER_CLICKED_CLEAR_PLAYLIST'
export const USER_CLICKED_PLAYLIST_TRACK = 'USER_CLICKED_PLAYLIST_TRACK'

export const IPFS_DOWLOADED_TRACK = 'IPFS_DOWNLOADED_TRACK'

export const PLAYER_UPDATED_BUFFER = 'PLAYER_UPDATED_BUFFER'
export const PLAYER_ENDED_PLAYBACK = 'PLAYER_ENDED_PLAYBACK'

export const USER_CLICKED_CLOSE_APP = 'USER_CLICKED_CLOSE_APP'
