# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:

  # ТЕСТЫ

  test:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn
      - run: yarn test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  # БИЛД +- РЕЛИЗ

  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: sudo apt-get install wine
      - run: yarn
      - run: if [[ ! -z $CIRCLE_PULL_REQUEST ]]; then unset GH_TOKEN ; fi
      - run: if [[ ! -z $CIRCLE_TAG ]]; then export EP_PRELEASE=true ; fi
      - run: yarn build --lin --win
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2

  # PRERELEASE

  prerelease:
    jobs:
      - test:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+\-\d+$/
            branches:
              only: /^v\d+\.\d+\.\d+\-\d+$/
      - build:
          requires:
            - test
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+\-\d+$/
            branches:
              only: /^v\d+\.\d+\.\d+\-\d+$/


  # DEVELOPMENT

  development:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master

  # PRODUCTION

  production:
    jobs:
      - build:
          filters:
            branches:
              only:
                - production
