# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  install:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo
    steps:
      - run: yarn test

  build:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo
    steps:
      - run: yarn build

workflows:
  version: 2

  # TAG PRERELEASE

  prerelease:
    jobs:
      - install:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+\-\d+$/
      - test:
          requires:
            - install
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+\-\d+$/
      - build:
          requires:
            - install
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+\-\d+$/

  # TEST ONLY

  test-only:
    jobs:
      - install:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+\-\d+$/
            branches:
              only:
                - master
                - production
      - test:
          requires:
            - install
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+\-\d+$/
            branches:
              only:
                - master
                - production
