import { ENV_DEVELOPMENT, ENV_TESTING, ENV_PRODUCTION } from './data/constants'

let ACTUAL_ENVIRONMENT

switch (process.env.NODE_ENV) {
  case ENV_DEVELOPMENT:
    ACTUAL_ENVIRONMENT = ENV_DEVELOPMENT
    break
  case ENV_PRODUCTION:
    ACTUAL_ENVIRONMENT = ENV_TESTING
    break
  default:
    ACTUAL_ENVIRONMENT = ENV_PRODUCTION
}

export const ENVIRONMENT = ACTUAL_ENVIRONMENT
